baseURL = 'https://ultrablur.github.io/'
languageCode = 'en-us'
title = '高胡宇晨｜Gao Huyuchen'
theme = 'sam'  
enableEmoji = true

pygmentsStyle            = "monokai"                        #   
pygmentsCodefences       = true

[[params.videoBackground.sources]]
    source  = "/WebBG_V06.mp4" # Your video file
    type    = "video/mp4"
    poster  = "/WebBG.jpg" # The image to show when the video isn't playing

[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0)" # optional


[params]
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = ""

[[params.mainMenu]]
    link = "/posts/"
    text = "posts"

[[params.mainMenu]]
    link = "/gallery/"
    text = "gallery"

[[params.mainMenu]]
    link = "/archive"
    text = "archive"

[[params.mainMenu]]
    link = "/about"
    text = "Gao Huyuchen"

