baseURL = 'https://ultrablur.github.io/'
languageCode = 'en-us'
title = 'Gao Huyuchen'
theme = 'sam'  

pygmentsStyle            = "monokai"                        #   
pygmentsCodefences       = true

[params]
    homepage             = "main"                           # What to call the home page link, link will not be rendered if empty
    footerText           = ""

[[params.mainMenu]]
    link = "/posts/"
    text = "posts"

[[params.mainMenu]]
    link = "/gallery/"
    text = "gallery"

[[params.mainMenu]]
    link = "/archive"
    text = "archive"

[[params.mainMenu]]
    link = "/about"
    text = "Gao Huyuchen"

[[params.mainMenu]]
    link = "/googleb240e5e97cf7d33b"
    text = "GSC"
